### ISSUE TITLE
怎么发布新帖？

### ISSUE THREAD

**Issue by luckypoem** [bingoogolapple/bga_issue_blog#51]
HI.

 我在这里https://github.com/luckypoem/bga_issue_blog/issues/1 ，发表了issue, 可https://luckypoem.github.io/bga_issue_blog并未出现
‘测试’这个帖子，怎么回事呢？
如何更新博客网站？
谢谢回复！

**Comment by bingoogolapple** [comment]
@luckypoem 需要按照 read 里的说明改下配置，重新打包。你目前只是把仓库克隆了，但所有配置信息都还是指向了我的 issue 仓库

**Comment by luckypoem** [comment]
我在这里https://github.com/luckypoem/bga_issue_blog/blob/gh-pages/src/store/modules/account.js 改了配置信息，难道是没改对？

**Comment by bingoogolapple** [comment]
@luckypoem 改了后有重新构建吗

方便的话加微信说    shangdixiaozhushou

**Comment by briteming** [comment]
hi.

我改为使用nvm了。不过运行npm run dev遇到错误，如何修复？

root@racknerd-626f077:~# cd bga_issue_blog
root@racknerd-626f077:~/bga_issue_blog# ls
个人博客.sketch  config  index.html    package.json       README.md  static
build            docs    node_modules  package-lock.json  src
root@racknerd-626f077:~/bga_issue_blog# npm --version
6.14.16
root@racknerd-626f077:~/bga_issue_blog# npm run dev

> bga-issue-blog@1.0.0 dev /root/bga_issue_blog
> node build/dev-server.js

/root/bga_issue_blog/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:26
                    next?.(err);
                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/bga_issue_blog/node_modules/http-proxy-middleware/dist/factory.js:4:33)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bga-issue-blog@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bga-issue-blog@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2025-01-19T19_51_09_405Z-debug.log
root@racknerd-626f077:~/bga_issue_blog# node --version
v12.22.12
root@racknerd-626f077:~/bga_issue_blog#
